#!/bin/sh

var_chrony_user="github.com/cloudboss/easyto/preinit/service.ChronyUser=${CHRONY_USER}"
var_ssh_dir="github.com/cloudboss/easyto/preinit/service.SSHDir=${OPENSSH_PRIVSEP_DIR}"
var_ssh_user="github.com/cloudboss/easyto/preinit/service.SSHUser=${OPENSSH_PRIVSEP_USER}"
ldflags_vars="-X ${var_chrony_user} -X ${var_ssh_dir} -X ${var_ssh_user}"
go build -o ${DIR_OUT}/preinit \
    -ldflags "${ldflags_vars} -linkmode external -extldflags -static -s -w" .
