#!/bin/sh

var_dir_et_root="github.com/cloudboss/easyto/pkg/constants.DirETRoot=${DIR_ET_ROOT}"
ldflags_vars="-X ${var_dir_et_root}"
go build -o ${DIR_OUT}/easyto -ldflags "${ldflags_vars} -s -w" ./cmd/easyto
