#!/bin/sh

set -e

export CFLAGS=-static
export LDFLAGS=-s
./configure \
    --chronyrundir=${CHRONYRUNDIR} \
    --localstatedir=${LOCALSTATEDIR} \
    --sysconfdir=${SYSCONFDIR} \
    --with-pidfile=${CHRONYRUNDIR}/chronyd.pid \
    --with-user=${CHRONY_USER}
make -j$(nproc)
