#!/bin/sh

var_chrony_user="github.com/cloudboss/easyto/preinit/service.ChronyUser=${CHRONY_USER}"
ldflags_vars="-X ${var_chrony_user}"
go build -o ${DIR_OUT}/preinit \
    -ldflags "${ldflags_vars} -linkmode external -extldflags -static -s -w" .
