#!/bin/sh

set -e

./configure LDFLAGS="--static -s" \
    --prefix=${DIR_ET_ROOT} \
    --disable-log-client \
    --disable-log-server \
    --disable-shared \
    --enable-static \
    --enable-zlib=static \
    --sysconfdir=${DIR_ET_ROOT}/etc \
    --with-logpath=${DIR_ET_ROOT}/var/log \
    --with-rundir=/run && \
    make -j$(nproc)
