#!/bin/sh

var_chrony_user="github.com/cloudboss/easyto/pkg/constants.ChronyUser=${CHRONY_USER}"
var_ssh_dir="github.com/cloudboss/easyto/pkg/constants.SSHPrivsepDir=${OPENSSH_PRIVSEP_DIR}"
var_ssh_user="github.com/cloudboss/easyto/pkg/constants.SSHPrivsepUser=${OPENSSH_PRIVSEP_USER}"
var_dir_et_root="github.com/cloudboss/easyto/pkg/constants.DirETRoot=${DIR_ET_ROOT}"
ldflags_vars="-X ${var_chrony_user} -X ${var_ssh_dir} -X ${var_ssh_user} -X ${var_dir_et_root}"
go build -o ${DIR_OUT}/init \
    -ldflags "${ldflags_vars} -linkmode external -extldflags -static -s -w" ./cmd/initial
