#!/bin/sh -e

fail()
{
    echo >&2 "${1}"
    exit 1
}

files_missing=
for f in ${ASSET_FILES}; do
    [ -f ${ASSET_DIR}/${f} ] || files_missing="${files_missing} ${f}"
done
[ -z "${files_missing}" ] || fail "Files missing in ${ASSET_DIR}: ${files_missing}"

chmod 0755 ${EXEC_CONVERTER}

apt-get update
apt-get install -y --no-install-recommends \
    dosfstools \
    parted

ROOT_DEVICE=$(readlink -f ${ROOT_DEVICE})

[ -n "$(blkid -s PTTYPE -o value ${ROOT_DEVICE})" ] || \
    parted ${ROOT_DEVICE} mklabel gpt

[ -n "$(blkid -s PARTUUID -o value ${ROOT_DEVICE}p1)" ] || \
    parted ${ROOT_DEVICE} mkpart efi fat16 1MiB 257MiB set 1 esp on

[ -n "$(blkid -s PARTUUID -o value ${ROOT_DEVICE}p2)" ] || \
    parted ${ROOT_DEVICE} mkpart root ext4 257MiB 100%

parted ${ROOT_DEVICE} print

[ -n "$(blkid -s TYPE -o value ${ROOT_DEVICE}p1)" ] || \
    mkfs -t vfat ${ROOT_DEVICE}p1

[ -n "$(blkid -s TYPE -o value ${ROOT_DEVICE}p2)" ] || \
    mkfs -t ext4 ${ROOT_DEVICE}p2

mountpoint -q /mnt || mount ${ROOT_DEVICE}p2 /mnt
mkdir -p -m 0755 /mnt/boot
mountpoint -q /mnt/boot || mount ${ROOT_DEVICE}p1 /mnt/boot

mkdir -p -m 0755 /mnt/__cb__

${EXEC_CONVERTER} \
    --asset-dir ${ASSET_DIR} \
    --container-image ${CONTAINER_IMAGE} \
    --login-user ${LOGIN_USER} \
    --login-shell ${LOGIN_SHELL} \
    --services ${SERVICES} \
    --vm-image-device ${ROOT_DEVICE}

ls -l /mnt
ls -l /mnt/__cb__
find /mnt/boot -ls
cat /mnt/boot/loader/entries/cb.conf

umount /mnt/boot
umount /mnt
