#!/bin/sh -e

if [ "${DEBUG}" = "true" ]; then
    set -x
fi

fail()
{
    echo >&2 "${1}"
    exit 1
}

files_missing=
for f in ${ASSET_FILES}; do
    [ -f ${ASSET_DIR}/${f} ] || files_missing="${files_missing} ${f}"
done
[ -z "${files_missing}" ] || fail "Files missing in ${ASSET_DIR}: ${files_missing}"

chmod 0755 ${EXEC_CTR2DISK}

[ "${DEBUG}" = "true" ] && debug_arg=--debug

${EXEC_CTR2DISK} \
    --asset-dir=${ASSET_DIR} \
    --container-image=${CONTAINER_IMAGE} \
    --login-user=${LOGIN_USER} \
    --login-shell=${LOGIN_SHELL} \
    --services=${SERVICES} \
    --vm-image-device=${ROOT_DEVICE} \
    ${debug_arg}

if [ "${DEBUG}" = "true" ]; then
    ls -la /mnt
    find /mnt/boot -ls
    cat /mnt/boot/loader/entries/cb.conf
fi

umount /mnt/boot
umount /mnt
